### ISSUE TITLE
Comparison to Exq

### ISSUE THREAD

**Issue by benwilson512** [edgurgel/verk#2]
Hey!

More of question than anything else, could you comment a bit on the differences between this library and exq?

Thanks!

**Comment by edgurgel** [comment]
The main focus of verk is to always perform the job at least once. That's why we use a lot of Redis Lua scripting so Verk never has the job outside of Redis.

We wanted to keep things simple and use poolboy(or any other solid pool library) to control the lifetime of our workers. This allow us to focus on managing the jobs and keep the processes hierarchy simple and isolated so restarts/crashes on one "processing queue" does not bring down the others. That's why the supervision tree is based on the defined queues.

And finally we didn't want to maintain a web-api/ember app as part of the main project.

It felt easier to start from scratch than use exq (at least when we thought on using/adapting exq: 3/4 months ago).
