### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ricn** [edgurgel/verk#48]
Sidekiq has a few options for testing workers: https://github.com/mperham/sidekiq/wiki/Testing

Do you have any plans to implement something similar or do you have a better approach to deal with workers when running tests?

**Comment by edgurgel** [comment]
That's a great question. I have no plans but I would be glad to work on something like this :+1:

**Comment by edgurgel** [comment]
Testing an actual worker should be easy as testing a function of a module cause that's what it is. 

The other case would be testing the fact that you enqueued a job. If Verk is running the queue it will try to process the job. A possible solution is to configure Verk to use a different Redis database "127.0.0.1/5" and configure the queues to be empty so that no queue will be processed. Something like this:

`config.exs`
```elixir
if Mix.env == :test do
  config :verk, queues: [], redis_url: "redis://127.0.0.1:6379/5"
end
```

Then one could use `Verk.Queue` to inspect what's inside the queue:

https://github.com/edgurgel/verk/blob/master/lib/verk/queue.ex

`assert Verk.Queue.range("my_queue") == [%Verk.Job{...}]`

Would this be helpful to add to a wiki page or something?

**Comment by ricn** [comment]
Thanks! I can try it out and see if it "feels" good to test it like this. I think it would be very helpful to add to a wiki page or in the readme.

**Comment by ricn** [comment]
Now I have written a couple of tests. I did it like this:
`test.exs`
`config :verk, queues: [], redis_url: "redis://127.0.0.1:6379/5"`

In the setup block in the test file I also added `Verk.Queue.clear("default")` because I got just more and more added jobs when calling `Verk.Queue.range(:default)`

**Comment by edgurgel** [comment]
Great! I should warn that I have plans to soon change every "data set" module like Verk.Queue, Verk.ScheduledSet, etc to have "clear!" and "clear!" so that one will return `{:ok, data}` or `{:error ,reason}` and the `!` one will simply throw an error if it failed. Basically one will use `Redix.command` and the other one `Redix.command!`. This will be a breaking change that I have to or people will need to try/catch if they want to treat the error case and try/catching is not the best way for an API.

**Comment by DavidAntaramian** [comment]
One clarification on the above is that if you use environment-specific configurations on top of `config/config.exs`, just setting `queues` to `[]` in a `config/test.exs` file will not prevent Verk from executing workers. When compiling the configuration Mix will _merge_ it with the previously defined Keyword list in the general configuration file, not substitute it. I ran into this snag today trying to figure out why Verk was still running during tests. Essentially:

```elixir
# config/config.exs
config :verk,
  queues: [elixir: 25],
  poll_interval: 5000,
  node_id: "1",
  redis: System.get_env("REDIS_URL")
```

```elixir
# config/test.exs
config :verk,
  queues: [],
  redis_url: "redis://localhost:6379/3"
```

Even in the test environment, the value of `:queues` will still be `[elixir: 25]` because it performs a merge. For anyone in this situation, the solution is to set explicitly defined queues to `0` in the test environment configuration:

```elixir
# config/test.exs
config :verk,
  queues: [elixir: 0],
  redis_url: "redis://localhost:6379/3"
```

**Comment by edgurgel** [comment]
Good point. A pretty common way to setup config files is to have `dev.exs`, `prod.exs`, `test.exs` and require it from `config.exs`. This way there's no merge. I think `phoenix.new` does this as initial structure.

**Comment by DavidAntaramian** [comment]
@edgurgel Sorry, I should have been more specific. That's the type of configuration I am referring to in the above; I didn't include the portion of `config.exs` which performs the `import_config`. There is a merge that occurs when using this method, although I didn't realize it was a deep merge.

**Comment by edgurgel** [comment]
Yeah Mix will merge the values. I usually separate the configuration completely and leave just the ones that are exactly the same for all environments on `config.exs`. So no verk config on the config.exs but one for each environment.

**Comment by edgurgel** [comment]
I'm closing this issue as there's no clear action to be taken .If we need more docs feel free to send a PR to change the README. Cheers!
